package artistry.enums;

public enum PersonRole {

	SCRUM_MASTER, DEVELOPER, AGILE_TEAM_MEMBER, PRODUCT_OWNER, RTE, STE, PRODUCT_MANAGER, TESTER, BUSINESS_OWNER, CUSTOMER, SOLUTION_MANAGER, SUPPLIER, PORTFOLIO_MANAGER, EPIC_OWNER, ENTERPRISE_ARCHITECT, UX, AGILE_LEADER, AGILE_COACH;

}
