package artistry.enums;

public enum Role {

	SCRUM_MASTER, DEVELOPER, AGILE_TEAM_MEMBER, PRODUCT_OWNER, RTE, STE, PRODUCT_MANAGER, TESTER, BUSINESS_OWNER, CUSTOMER, SOLUTION_MANAGER, SUPPLIER, PORTFOLIO_MANAGER, EPIC_OWNER, ENTERPRISE_ARCHITECT, UX, AGILE_LEADER, AGILE_COACH, DEVELOPMENT_MANAGER, TEAM_LEAD, TRANSLATOR, MOBILE_IOS_DEV, MOBILE_ANDROID_DEV, MOBILE_ANDROID_KOT_DEV, CTO, CEO, DEVOPS_ENGINEER, MARKETING, MARKETING_MANAGER, ANALYTICS, ANALYTICS_MANAGER, REPORTING, GIS, CONSULTANT, DBA;

}
