/** This class was generated by GenTest@Mobacar */
package artistry.webhook;

import artistry.repositories.DestinationRepository;
import artistry.repositories.MessageRepository;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.mockito.Mockito.mock;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = MessageProcessor.class)
public class MessageProcessorTest {

	@Autowired
	private MessageProcessor underTest;

	@MockBean
	private DestinationRepository destinationRepository;

	@MockBean
	private MessageRepository messageRepository;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testMessageReceivedListener() throws Exception {
		// given
		MessageReceivedEvent messageReceivedEvent = mock(MessageReceivedEvent.class);
		// when
		underTest.messageReceivedListener(messageReceivedEvent);
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

	@Test
	public void testScheduledMessagesProcessor() throws Exception {
		// given
		// when
		underTest.scheduledMessagesProcessor();
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

}
