/** This class was generated by GenTest@Mobacar */
package artistry.webhook;

import artistry.models.Destination;
import artistry.models.WebHookMessage;
import artistry.repositories.DestinationRepository;
import artistry.repositories.MessageRepository;
import java.nio.charset.*;
import java.util.*;
import java.util.Date;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.io.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.boot.web.client.RestTemplateBuilder;
import org.springframework.context.event.EventListener;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = MessageProcessor.class)
public class MessageProcessorTest {

	@Autowired
	private MessageProcessor underTest;

	@MockBean
	private DestinationRepository destinationRepository;

	@MockBean
	private MessageRepository messageRepository;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testMessageReceivedListener() throws Exception {
		// given
		MessageReceivedEvent messageReceivedEvent = mock(MessageReceivedEvent.class);
		// when
		underTest.messageReceivedListener(messageReceivedEvent);
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

	@Test
	public void testScheduledMessagesProcessor() throws Exception {
		// given
		// when
		underTest.scheduledMessagesProcessor();
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

}
