/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import io.micrometer.core.instrument.MeterRegistry;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = MetricsConfig.class)
public class MetricsConfigTest {

	@Autowired
	private MetricsConfig underTest;
	

	@Value("${spring.application.name}")
	private String serviceId;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testMetricsCommonTags() throws Exception {
		// given
		// when
		MeterRegistryCustomizer<MeterRegistry> actual = underTest.metricsCommonTags();
		// then
		assertNotNull(actual);
	}

}
