/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.neo4j.ogm.session.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.neo4j.transaction.Neo4jTransactionManager;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = Neo4jConfiguration.class)
public class Neo4jConfigurationTest {

	@Autowired
	private Neo4jConfiguration underTest;
	

	@Value("${spring.data.neo4j.password}")
	private String dbpass;

	@Value("${spring.data.neo4j.username}")
	private String dbuser;

	@Value("${spring.data.neo4j.uri}")
	private String uri;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testConfiguration() throws Exception {
		// given
		// when
		org.neo4j.ogm.config.Configuration actual = underTest.configuration();
		// then
		assertNotNull(actual);
	}

	@Test
	public void testSessionFactory() throws Exception {
		// given
		// when
		SessionFactory actual = underTest.sessionFactory();
		// then
		assertNotNull(actual);
	}

	@Test
	public void testTransactionManager() throws Exception {
		// given
		// when
		Neo4jTransactionManager actual = underTest.transactionManager();
		// then
		assertNotNull(actual);
	}

}
