/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = RestTemplateConfiguration.class)
public class RestTemplateConfigurationTest {

	@Autowired
	private RestTemplateConfiguration underTest;
	

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testGetRestClient() throws Exception {
		// given
		// when
		RestTemplate actual = underTest.getRestClient();
		// then
		assertNotNull(actual);
	}

}
