/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import com.fasterxml.classmate.TypeResolver;
import com.netflix.hystrix.strategy.metrics.HystrixMetricsPublisher;
import java.nio.charset.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.io.*;
import org.apache.commons.lang3.StringUtils;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.UiConfiguration;
import springfox.documentation.swagger.web.UiConfigurationBuilder;
import springfox.documentation.swagger2.annotations.EnableSwagger2;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = {SwaggerConfiguration.class, TypeResolver.class})
public class SwaggerConfigurationTest {

	@Autowired
	private SwaggerConfiguration underTest;
	
	@MockBean
	private RequestMappingInfoHandlerMapping requestMappingInfoHandlerMapping;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testArtistryApi() throws Exception {
		// given
		// when
		Docket actual = underTest.artistryApi();
		// then
		assertNotNull(actual);
	}

	@Test
	public void testUiConfig() throws Exception {
		// given
		// when
		UiConfiguration actual = underTest.uiConfig();
		// then
		assertNotNull(actual);
	}

}
