/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import com.fasterxml.classmate.TypeResolver;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger.web.UiConfiguration;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = {SwaggerConfiguration.class, TypeResolver.class})
public class SwaggerConfigurationTest {

	@Autowired
	private SwaggerConfiguration underTest;
	
	@MockBean
	private RequestMappingInfoHandlerMapping requestMappingInfoHandlerMapping;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testArtistryApi() throws Exception {
		// given
		// when
		Docket actual = underTest.artistryApi();
		// then
		assertNotNull(actual);
	}

	@Test
	public void testUiConfig() throws Exception {
		// given
		// when
		UiConfiguration actual = underTest.uiConfig();
		// then
		assertNotNull(actual);
	}

}
