/** This class was generated by GenTest@Mobacar */
package artistry.configuration;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.concurrent.Executor;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = WebHookConfiguration.class)
public class WebHookConfigurationTest {

	@Autowired
	private WebHookConfiguration underTest;
	

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testGetAsyncExecutor() throws Exception {
		// given
		// when
		Executor actual = underTest.getAsyncExecutor();
		// then
		assertNotNull(actual);
	}

}
