server:
  port: 9988
  compression:
    enabled: true
---

logging:
  level: 
    org.springframework.web: DEBUG
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE

spring:
  profiles: dev
  data:
    neo4j:
      username: neo4j 
      password: hello
      uri: localhost
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
    hostname: localhost
       
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
jira:
  url: http://myjira.company.com
  username: myusername
  password: sometrickyPassword
  
---
  
spring:
  profiles: test
  data:
    neo4j:
      username: neo4j 
      password: hello
      uri: localhost
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
    hostname: localhost
       
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
jira:
  url: http://myjira.company.com
  username: myusername
  password: sometrickyPassword
  
---

spring:
  profiles: docker
  data:
    neo4j:
      username: neo4j 
      password: hello
      uri: neo4j
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
    hostname: registry
       
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
jira:
  url: http://myjira.company.com
  username: myusername
  password: sometrickyPassword