/** This class was generated by GenTest@Mobacar */
package artistry.services;

import artistry.models.ConfluenceSpaces;
import artistry.models.NewConfluencePage;
import artistry.utils.JiraUtils;
import java.nio.charset.*;
import java.util.*;
import java.util.Collections;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.io.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = ConfluenceService.class)
public class ConfluenceServiceTest {

	@Autowired
	private ConfluenceService underTest;

	@Value("${jira.url}")
	private String jiraUrl;

	@MockBean
	private RestTemplate rt;

	@MockBean
	private JiraUtils utils;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testCreatePage() throws Exception {
		// given
		NewConfluencePage page = new NewConfluencePage();
		// when
		NewConfluencePage actual = underTest.createPage(page);
		// then
		assertNotNull(actual);
	}

	@Test
	public void testGetDocumentById() throws Exception {
		// given
		String id = "id";
		// when
		String actual = underTest.getDocumentById(id);
		// then
		assertEquals("", actual);
	}

	@Test
	public void testGetSpaceByKey() throws Exception {
		// given
		String key = "key";
		// when
		String actual = underTest.getSpaceByKey(key);
		// then
		assertEquals("", actual);
	}

	@Test
	public void testGetSpaceContent() throws Exception {
		// given
		String key = "key";
		// when
		String actual = underTest.getSpaceContent(key);
		// then
		assertEquals("", actual);
	}

	@Test
	public void testGetSpaces() throws Exception {
		// given
		// when
		ConfluenceSpaces actual = underTest.getSpaces();
		// then
		assertNotNull(actual);
	}

}
