/** This class was generated by GenTest@Mobacar */
package artistry.services;

import artistry.configuration.StorageProperties;
import artistry.exceptions.StorageException;
import artistry.exceptions.StorageFileNotFoundException;
import artistry.utils.StorageService;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.nio.charset.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Stream;
import org.apache.commons.io.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.core.io.Resource;
import org.springframework.core.io.UrlResource;
import org.springframework.stereotype.Service;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.util.FileSystemUtils;
import org.springframework.util.StringUtils;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.multipart.MultipartFile;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = FileSystemStorageService.class)
public class FileSystemStorageServiceTest {

	@Autowired
	private FileSystemStorageService underTest;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testDeleteAll() throws Exception {
		// given
		// when
		underTest.deleteAll();
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

	@Test
	public void testInit() throws Exception {
		// given
		// when
		underTest.init();
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

	@Test
	public void testLoad() throws Exception {
		// given
		String filename = "filename";
		// when
		Path actual = underTest.load(filename);
		// then
		assertNotNull(actual);
	}

	@Test
	public void testLoadAll() throws Exception {
		// given
		// when
		Stream<Path> actual = underTest.loadAll();
		// then
		assertNotNull(actual);
	}

	@Test
	public void testLoadAsResource() throws Exception {
		// given
		String filename = "filename";
		// when
		Resource actual = underTest.loadAsResource(filename);
		// then
		assertNotNull(actual);
	}

	@Test
	public void testStore() throws Exception {
		// given
		MultipartFile file = new MockMultipartFile("fileName", "content".getBytes());
		// when
		underTest.store(file);
		// then
		// TODO add meaningful assert or verify(mock).method();
	}

}
