/** This class was generated by GenTest@Mobacar */
package artistry.services;

import artistry.models.SprintEntry;
import artistry.models.VelocityEntry;
import artistry.repositories.SprintRepository;
import artistry.repositories.VelocityRepository;
import artistry.utils.JiraUtils;
import org.json.JSONObject;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;

import java.util.List;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = SprintService.class)
public class SprintServiceTest {

	@Autowired
	private SprintService underTest;

	@Value("${jira.url}")
	private String jiraUrl;

	@MockBean
	private RestTemplate rt;

	@MockBean
	private SprintRepository srepo;

	@MockBean
	private JiraUtils utils;

	@MockBean
	private VelocityRepository vrepo;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testGetSprints() throws Exception {
		// given
		String teamid = "teamid";
		// when
		JSONObject actual = underTest.getSprints(teamid);
		// then
		assertNotNull(actual);
	}

	@Test
	public void testParseSprints() throws Exception {
		// given
		JSONObject sprints = new JSONObject("{}");
		String teamid = "teamid";
		// when
		List<SprintEntry> actual = underTest.parseSprints(sprints, teamid);
		// then
		assertArrayEquals(new Object[]{}, actual.toArray());
	}

	@Test
	public void testParseVelocities() throws Exception {
		// given
		JSONObject sprints = new JSONObject("{}");
		String teamid = "teamid";
		// when
		List<VelocityEntry> actual = underTest.parseVelocities(sprints, teamid);
		// then
		assertArrayEquals(new Object[]{}, actual.toArray());
	}

}
