/** This class was generated by GenTest@Mobacar */
package artistry.services;

import artistry.models.Train;
import artistry.repositories.TrainRepository;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertNotNull;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = TrainService.class)
public class TrainServiceTest {

	@Autowired
	private TrainService underTest;

	@MockBean
	private TrainRepository trainRepo;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testFindByName() throws Exception {
		// given
		String name = "name";
		// when
		Train actual = underTest.findByName(name);
		// then
		assertNotNull(actual);
	}

}
