/** This class was generated by GenTest@Mobacar */
package artistry.utils;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import java.io.File;
import java.util.zip.ZipEntry;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.mock;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = DownloadService.class)
public class DownloadServiceTest {

	@Autowired
	private DownloadService underTest;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testDownload() throws Exception {
		// given
		String url = "url";
		String code = "code";
		// when
		String actual = underTest.download(url, code);
		// then
		assertEquals("", actual);
	}

	@Test
	public void testNewFile() throws Exception {
		// given
		File destinationDir = mock(File.class);
		ZipEntry zipEntry = mock(ZipEntry.class);
		// when
		File actual = underTest.newFile(destinationDir, zipEntry);
		// then
		assertNotNull(actual);
	}

}
