/** This class was generated by GenTest@Mobacar */
package artistry.utils;

import artistry.configuration.StorageProperties;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.nio.charset.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import java.util.zip.ZipEntry;
import org.apache.commons.io.*;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.stereotype.Component;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = DownloadService.class)
public class DownloadServiceTest {

	@Autowired
	private DownloadService underTest;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testDownload() throws Exception {
		// given
		String url = "url";
		String code = "code";
		// when
		String actual = underTest.download(url, code);
		// then
		assertEquals("", actual);
	}

	@Test
	public void testNewFile() throws Exception {
		// given
		File destinationDir = mock(File.class);
		ZipEntry zipEntry = mock(ZipEntry.class);
		// when
		File actual = underTest.newFile(destinationDir, zipEntry);
		// then
		assertNotNull(actual);
	}

}
