/** This class was generated by GenTest@Mobacar */
package artistry.utils;

import java.awt.*;
import java.awt.geom.Point2D;
import java.awt.geom.Rectangle2D;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

public class GoogleTileUtilsTest {

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testGetPixelOffsetInTile() throws Exception {
		// given
		double lat = 0d;
		double lng = 0d;
		int zoom = 0;
		// when
		Point actual = GoogleTileUtils.getPixelOffsetInTile(lat, lng, zoom);
		// then
		assertNotNull(actual);
	}

	@Test
	public void testGetTileRect() throws Exception {
		// given
		int x = 0;
		int y = 0;
		int zoom = 0;
		// when
		java.awt.geom.Rectangle2D.Double actual = GoogleTileUtils.getTileRect(x, y, zoom);
		// then
		assertNotNull(actual);
	}

}
