/** This class was generated by GenTest@Mobacar */
package artistry.utils;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;

import static org.junit.Assert.assertEquals;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = JiraUtils.class)
public class JiraUtilsTest {

	@Autowired
	private JiraUtils underTest;

	@Value("${jira.password}")
	private String jiraPass;

	@Value("${jira.username}")
	private String jiraUser;

	@Before
	public void setupTest() {
		// prepare test
	}

	@Test
	public void testMakeBase64Credentials() throws Exception {
		// given
		// when
		String actual = underTest.makeBase64Credentials();
		// then
		assertEquals("", actual);
	}

}
