/** This class was generated by GenTest@Mobacar */
package artistry.models;

import artistry.enums.AddressType;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class AddressTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private Address underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetAddressLine() throws Exception {
		// given
		Set<String> value = new TreeSet<>();
		underTest.setAddressLine(value);
		// when
		Set<String> actual = underTest.getAddressLine();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetAddressType() throws Exception {
		// given
		AddressType value = AddressType.LOCALBUSINESS;
		underTest.setAddressType(value);
		// when
		AddressType actual = underTest.getAddressType();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetCity() throws Exception {
		// given
		String value = "city";
		underTest.setCity(value);
		// when
		String actual = underTest.getCity();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetCountry() throws Exception {
		// given
		Country value = new Country();
		underTest.setCountry(value);
		// when
		Country actual = underTest.getCountry();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetFullAddress() throws Exception {
		// given
		String value = "fullAddress";
		underTest.setFullAddress(value);
		// when
		String actual = underTest.getFullAddress();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetLatitude() throws Exception {
		// given
		Double value = 0d;
		underTest.setLatitude(value);
		// when
		Double actual = underTest.getLatitude();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetLongitude() throws Exception {
		// given
		Double value = 0d;
		underTest.setLongitude(value);
		// when
		Double actual = underTest.getLongitude();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetPostalCode() throws Exception {
		// given
		String value = "postalCode";
		underTest.setPostalCode(value);
		// when
		String actual = underTest.getPostalCode();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testIsPostalAddress() throws Exception {
		// given
		boolean value = false;
		underTest.setPostalAddress(value);
		// when
		boolean actual = underTest.isPostalAddress();
		// then
		assertEquals(value, actual);
	}

}
