/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class DestinationTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private Destination underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetMessages() throws Exception {
		// given
		List<WebHookMessage> value = Arrays.asList();
		underTest.setMessages(value);
		// when
		List<WebHookMessage> actual = underTest.getMessages();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetUrl() throws Exception {
		// given
		String value = "url";
		underTest.setUrl(value);
		// when
		String actual = underTest.getUrl();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testIsOnline() throws Exception {
		// given
		boolean value = false;
		underTest.setOnline(value);
		// when
		boolean actual = underTest.isOnline();
		// then
		assertEquals(value, actual);
	}

}
