/** This class was generated by GenTest@Mobacar */
package artistry.models;

import java.util.*;
import java.util.Arrays;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.lang3.SerializationUtils;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.mockito.runners.MockitoJUnitRunner;
import org.neo4j.ogm.annotation.GeneratedValue;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.NodeEntity;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(MockitoJUnitRunner.class)
public class EmailAddressTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private EmailAddress underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetEmergencyContactEmail() throws Exception {
		// given
		String value = "emergencyContactEmail";
		underTest.setEmergencyContactEmail(value);
		// when
		String actual = underTest.getEmergencyContactEmail();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetPersonalEmail() throws Exception {
		// given
		String value = "personalEmail";
		underTest.setPersonalEmail(value);
		// when
		String actual = underTest.getPersonalEmail();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSupportEmail() throws Exception {
		// given
		String value = "supportEmail";
		underTest.setSupportEmail(value);
		// when
		String actual = underTest.getSupportEmail();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetTeamEmail() throws Exception {
		// given
		String value = "teamEmail";
		underTest.setTeamEmail(value);
		// when
		String actual = underTest.getTeamEmail();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetWorkEmail() throws Exception {
		// given
		String value = "workEmail";
		underTest.setWorkEmail(value);
		// when
		String actual = underTest.getWorkEmail();
		// then
		assertEquals(value, actual);
	}

}
