/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class JiraProjectsTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private JiraProjects underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetErrorOrComment() throws Exception {
		// given
		String value = "errorOrComment";
		underTest.setErrorOrComment(value);
		// when
		String actual = underTest.getErrorOrComment();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetMaxResults() throws Exception {
		// given
		int value = 0;
		underTest.setMaxResults(value);
		// when
		int actual = underTest.getMaxResults();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSelf() throws Exception {
		// given
		String value = "self";
		underTest.setSelf(value);
		// when
		String actual = underTest.getSelf();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetStartAt() throws Exception {
		// given
		int value = 0;
		underTest.setStartAt(value);
		// when
		int actual = underTest.getStartAt();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetTotal() throws Exception {
		// given
		int value = 0;
		underTest.setTotal(value);
		// when
		int actual = underTest.getTotal();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetValues() throws Exception {
		// given
		Set<JiraProject> value = new TreeSet<>();
		underTest.setValues(value);
		// when
		Set<JiraProject> actual = underTest.getValues();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testIsLast() throws Exception {
		// given
		boolean value = false;
		underTest.setLast(value);
		// when
		boolean actual = underTest.isLast();
		// then
		assertEquals(value, actual);
	}

}
