/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class JiraWebhookTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private JiraWebhook underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetEvents() throws Exception {
		// given
		Set<String> value = new TreeSet<>();
		underTest.setEvents(value);
		// when
		Set<String> actual = underTest.getEvents();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetFilters() throws Exception {
		// given
		JiraFilter value = new JiraFilter();
		underTest.setFilters(value);
		// when
		JiraFilter actual = underTest.getFilters();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetName() throws Exception {
		// given
		String value = "name";
		underTest.setName(value);
		// when
		String actual = underTest.getName();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetUrl() throws Exception {
		// given
		String value = "url";
		underTest.setUrl(value);
		// when
		String actual = underTest.getUrl();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testIsExcludeBody() throws Exception {
		// given
		boolean value = false;
		underTest.setExcludeBody(value);
		// when
		boolean actual = underTest.isExcludeBody();
		// then
		assertEquals(value, actual);
	}

}
