/** This class was generated by GenTest@Mobacar */
package artistry.models;

import java.util.*;
import java.util.Arrays;
import java.util.Date;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.lang3.SerializationUtils;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.mockito.runners.MockitoJUnitRunner;
import org.neo4j.ogm.annotation.GeneratedValue;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.NodeEntity;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(MockitoJUnitRunner.class)
public class KPITest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private KPI underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetAttachedDocumentation() throws Exception {
		// given
		Set<Document> value = new TreeSet<>();
		underTest.setAttachedDocumentation(value);
		// when
		Set<Document> actual = underTest.getAttachedDocumentation();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetCreationDate() throws Exception {
		// given
		Date value = new Date();
		underTest.setCreationDate(value);
		// when
		Date actual = underTest.getCreationDate();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetModificationDate() throws Exception {
		// given
		Date value = new Date();
		underTest.setModificationDate(value);
		// when
		Date actual = underTest.getModificationDate();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetObjective() throws Exception {
		// given
		String value = "objective";
		underTest.setObjective(value);
		// when
		String actual = underTest.getObjective();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetReview() throws Exception {
		// given
		Set<Document> value = new TreeSet<>();
		underTest.setReview(value);
		// when
		Set<Document> actual = underTest.getReview();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetStakeholders() throws Exception {
		// given
		Set<Person> value = new TreeSet<>();
		underTest.setStakeholders(value);
		// when
		Set<Person> actual = underTest.getStakeholders();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetVersion() throws Exception {
		// given
		int value = 0;
		underTest.setVersion(value);
		// when
		int actual = underTest.getVersion();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testIsActive() throws Exception {
		// given
		boolean value = false;
		underTest.setActive(value);
		// when
		boolean actual = underTest.isActive();
		// then
		assertEquals(value, actual);
	}

}
