/** This class was generated by GenTest@Mobacar */
package artistry.models;

import java.util.*;
import java.util.Arrays;
import java.util.Date;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;
import org.apache.commons.lang3.SerializationUtils;
import org.junit.*;
import org.junit.runner.RunWith;
import org.mockito.*;
import org.mockito.runners.MockitoJUnitRunner;
import org.neo4j.ogm.annotation.GeneratedValue;
import org.neo4j.ogm.annotation.Id;
import org.neo4j.ogm.annotation.NodeEntity;
import org.neo4j.ogm.annotation.Relationship;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Matchers.any;
import static org.mockito.Matchers.anyString;
import static org.mockito.Matchers.endsWith;
import static org.mockito.Matchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import utils.*;

@RunWith(MockitoJUnitRunner.class)
public class LargeSolutionTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private LargeSolution underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetCapabilities() throws Exception {
		// given
		Set<Capability> value = new TreeSet<>();
		underTest.setCapabilities(value);
		// when
		Set<Capability> actual = underTest.getCapabilities();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetCustomer() throws Exception {
		// given
		Person value = new Person();
		underTest.setCustomer(value);
		// when
		Person actual = underTest.getCustomer();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetInspectAndAdaptEvent() throws Exception {
		// given
		InspectAndAdapt value = new InspectAndAdapt();
		underTest.setInspectAndAdaptEvent(value);
		// when
		InspectAndAdapt actual = underTest.getInspectAndAdaptEvent();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetLargeSolutionName() throws Exception {
		// given
		String value = "largeSolutionName";
		underTest.setLargeSolutionName(value);
		// when
		String actual = underTest.getLargeSolutionName();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetNonFunctionalRequirements() throws Exception {
		// given
		Set<NonFunctionalRequirement> value = new TreeSet<>();
		underTest.setNonFunctionalRequirements(value);
		// when
		Set<NonFunctionalRequirement> actual = underTest.getNonFunctionalRequirements();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetPostPlanningDocuments() throws Exception {
		// given
		Set<Document> value = new TreeSet<>();
		underTest.setPostPlanningDocuments(value);
		// when
		Set<Document> actual = underTest.getPostPlanningDocuments();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetPrePlanningDocuments() throws Exception {
		// given
		Set<Document> value = new TreeSet<>();
		underTest.setPrePlanningDocuments(value);
		// when
		Set<Document> actual = underTest.getPrePlanningDocuments();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetPrograms() throws Exception {
		// given
		Set<Program> value = new TreeSet<>();
		underTest.setPrograms(value);
		// when
		Set<Program> actual = underTest.getPrograms();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetSolutionArchitect() throws Exception {
		// given
		Person value = new Person();
		underTest.setSolutionArchitect(value);
		// when
		Person actual = underTest.getSolutionArchitect();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSolutionBacklog() throws Exception {
		// given
		SolutionBacklog value = new SolutionBacklog();
		underTest.setSolutionBacklog(value);
		// when
		SolutionBacklog actual = underTest.getSolutionBacklog();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSolutionContext() throws Exception {
		// given
		Document value = new Document();
		underTest.setSolutionContext(value);
		// when
		Document actual = underTest.getSolutionContext();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSolutionDemo() throws Exception {
		// given
		Date value = new Date();
		underTest.setSolutionDemo(value);
		// when
		Date actual = underTest.getSolutionDemo();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSolutionEpics() throws Exception {
		// given
		Set<Epic> value = new TreeSet<>();
		underTest.setSolutionEpics(value);
		// when
		Set<Epic> actual = underTest.getSolutionEpics();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetSolutionIntent() throws Exception {
		// given
		Document value = new Document();
		underTest.setSolutionIntent(value);
		// when
		Document actual = underTest.getSolutionIntent();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSolutionManagement() throws Exception {
		// given
		Set<Person> value = new TreeSet<>();
		underTest.setSolutionManagement(value);
		// when
		Set<Person> actual = underTest.getSolutionManagement();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetSolutionTrainEngineer() throws Exception {
		// given
		Person value = new Person();
		underTest.setSolutionTrainEngineer(value);
		// when
		Person actual = underTest.getSolutionTrainEngineer();
		// then
		assertEquals(value, actual);
	}

}
