/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class PlanetTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private Planet underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetBiome() throws Exception {
		// given
		Set<Biome> value = new TreeSet<>();
		underTest.setBiome(value);
		// when
		Set<Biome> actual = underTest.getBiome();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetContinent() throws Exception {
		// given
		Set<Continent> value = new TreeSet<>();
		underTest.setContinent(value);
		// when
		Set<Continent> actual = underTest.getContinent();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetIsland() throws Exception {
		// given
		Set<Island> value = new TreeSet<>();
		underTest.setIsland(value);
		// when
		Set<Island> actual = underTest.getIsland();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetName() throws Exception {
		// given
		String value = "name";
		underTest.setName(value);
		// when
		String actual = underTest.getName();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetOcean() throws Exception {
		// given
		Set<Ocean> value = new TreeSet<>();
		underTest.setOcean(value);
		// when
		Set<Ocean> actual = underTest.getOcean();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

}
