/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.runners.MockitoJUnitRunner;

import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class StrategicThemeTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private StrategicTheme underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetCreationDate() throws Exception {
		// given
		Date value = new Date();
		underTest.setCreationDate(value);
		// when
		Date actual = underTest.getCreationDate();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSupportingDocumentation() throws Exception {
		// given
		Set<Document> value = new TreeSet<>();
		underTest.setSupportingDocumentation(value);
		// when
		Set<Document> actual = underTest.getSupportingDocumentation();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetThemeName() throws Exception {
		// given
		String value = "themeName";
		underTest.setThemeName(value);
		// when
		String actual = underTest.getThemeName();
		// then
		assertEquals(value, actual);
	}

}
