/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.Set;
import java.util.TreeSet;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class TrainTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private Train underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetName() throws Exception {
		// given
		String value = "name";
		underTest.setName(value);
		// when
		String actual = underTest.getName();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetPeopleAndLocations() throws Exception {
		// given
		Set<ImplementationTeam> value = new TreeSet<>();
		underTest.setPeopleAndLocations(value);
		// when
		Set<ImplementationTeam> actual = underTest.getPeopleAndLocations();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetPi() throws Exception {
		// given
		Set<ProgramIncrement> value = new TreeSet<>();
		underTest.setPi(value);
		// when
		Set<ProgramIncrement> actual = underTest.getPi();
		// then
		assertArrayEquals(value.toArray(), actual.toArray());
	}

	@Test
	public void testGetSolutionStatement() throws Exception {
		// given
		Document value = new Document();
		underTest.setSolutionStatement(value);
		// when
		Document actual = underTest.getSolutionStatement();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetTeamDesignStrategy() throws Exception {
		// given
		Document value = new Document();
		underTest.setTeamDesignStrategy(value);
		// when
		Document actual = underTest.getTeamDesignStrategy();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetVisionStatement() throws Exception {
		// given
		Document value = new Document();
		underTest.setVisionStatement(value);
		// when
		Document actual = underTest.getVisionStatement();
		// then
		assertEquals(value, actual);
	}

}
