/** This class was generated by GenTest@Mobacar */
package artistry.models;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class WatchesTest {

	/**
	 * If the class has a default constructor, then you don't need to instantiate it manually. InjectMocks annotation will do it.<br/>
	 * Otherwise use the {@link #setupTest()} method for creating the underTest object.
	 */
	@InjectMocks
	private Watches underTest;

	@Before
	public void setupTest() {
		// prepare test
		MockitoAnnotations.initMocks(this);
	}

	@Test
	public void testGetId() throws Exception {
		// given
		Long value = 0L;
		underTest.setId(value);
		// when
		Long actual = underTest.getId();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetIsWatching() throws Exception {
		// given
		Boolean value = false;
		underTest.setIsWatching(value);
		// when
		Boolean actual = underTest.getIsWatching();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetSelf() throws Exception {
		// given
		String value = "self";
		underTest.setSelf(value);
		// when
		String actual = underTest.getSelf();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetWatchCount() throws Exception {
		// given
		Integer value = 0;
		underTest.setWatchCount(value);
		// when
		Integer actual = underTest.getWatchCount();
		// then
		assertEquals(value, actual);
	}

	@Test
	public void testGetWatching() throws Exception {
		// given
		Boolean value = false;
		underTest.setWatching(value);
		// when
		Boolean actual = underTest.getWatching();
		// then
		assertEquals(value, actual);
	}

}
